### ISSUE TITLE
Consider allowing for chaining syntax when calling into an element method

### ISSUE THREAD

**Issue by KevinGrandon** [KevinGrandon/ghostjs#100]
Currently if you want element text you need to do something like:

``` js
let element = await waitForElement(selector)
let text = await element.text()
// And if you want it on one line:
let element = await (await waitForElement(selector)).text()
```

Instead, it would be nice to be able to do something like:

``` js
let text = await waitForElement(selector).text()
```

**Comment by vsilaev** [comment]
Currently it's pretty valid to write:
`let text = await ghost.waitForElement(selector).then( async el => el.text() )`
It's both less verbose and more readable

**Comment by KevinGrandon** [comment]
That's a great point and doesn't try to work around native  promise/async code with ugly hacks. Thanks for the suggestion, I'll add something like this to the readme.
