### ISSUE TITLE
Add support for throttling Network requests (in Chrome) 

### ISSUE THREAD

**Issue by akleiner2** [KevinGrandon/ghostjs#152]
Chrome Debugging Protocol has [`Network.emulateNetworkConditions`](https://chromedevtools.github.io/devtools-protocol/tot/Network/), which we could use to simulate 3G/2G speeds, etc. Would be good to have something along the lines of `ghost.emulateNetworkConditions()` which defers to the CDP.

**Comment by KevinGrandon** [comment]
If we can

**Comment by KevinGrandon** [comment]
This would be awesome! I assume that this function would take arguments for latency/upload/download?

This may also be possible in Firefox in the future: https://blog.nightly.mozilla.org/2016/11/07/simulate-slow-connections-with-the-network-throttling-tool/

Ideally we also expose some network connections that users can use as a pre-set along the options of the chrome tools:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/122602/28232839-b9c4e610-68a7-11e7-9282-6d39bc405595.png">
