### ISSUE TITLE
Filling forms within an iframe?

### ISSUE THREAD

**Issue by rationalthinker1** [KevinGrandon/ghostjs#167]
Hello,
I want to submit a form that is inside an iframe? Can ghostjs do that?

**Comment by KevinGrandon** [comment]
I believe you can use `ghost.usePage(url)` to change to the context of the iframe and script as normal. Would need to see a more in-depth example of what you're trying to do exactly, but this should work. LMK if it does't /w an example HTML file if you can't get this working, and we'll fix it.

**Comment by rationalthinker1** [comment]
Hello,
I can give you an example.

I want to autofill this site:
http://www.goodmanmfg.com/product-registration

The form is in the iframe. You can test it with serial_number = "1601176389" and installation date as "9/1/2016". I tried to fill the form but I couldn't do it because of the iframe.
